version: '2.4'

services:
    neoappli:
      image: rippergun/neonovis:7.4
      container_name: neoweb
      hostname: neoweb
      expose:
        - "9100"
      ports:
        - "80:80"
        - "443:443"
        - "8483:8483"
        - "2222:22" # ssh
    #  entrypoint:
      extra_hosts:
      - "www4.neonovis.lan:127.0.0.1"
      - "sebastien-ws.caumes.lan:127.0.0.1"
      - "vanina-ws.caumes.lan:127.0.0.1"
      volumes:
        - /home/projects:/home/projects
        - /home/ripper:/home/ripper
        - /tmp/mysql.sock:/tmp/mysql.sock
        - ./ssh:/root/.ssh/
        - ./composer:/root/.composer/
        - /home/projects/maxence/vhost.conf:/etc/apache2/sites-enabled/maxence.conf:ro
        - /home/projects/babyblog/vhost.conf:/etc/apache2/sites-enabled/babyblog.conf:ro
        - /home/projects/philippemorize/vhost.conf:/etc/apache2/sites-enabled/philippemorize.conf:ro
        - /home/projects/saisonsvives/vhost.conf:/etc/apache2/sites-enabled/saisonsvives.conf:ro
        - /home/projects/cms_php/vhost.conf:/etc/apache2/sites-enabled/neocms.conf:ro
        - /home/projects/NeoPrivateSf/vhost.conf:/etc/apache2/sites-enabled/neoprivatesf.conf:ro
        - /home/projects/NeoPrivateWsSf/vhost.conf:/etc/apache2/sites-enabled/neoprivatewssf.conf:ro
        - /home/projects/NeoServices/vhost.conf:/etc/apache2/sites-enabled/neoservices.conf:ro
        - /home/projects/cms_php_sf/vhost.conf:/etc/apache2/sites-enabled/cms_php_sf.conf:ro
        - /home/projects/phpmyadmin.conf:/etc/apache2/sites-enabled/phpmyadmin.conf:ro
        - /home/projects/server.crt:/etc/apache2/ssl/server.crt:ro
        - /home/projects/server.key:/etc/apache2/ssl/server.key:ro
      tty: true
      dns:
        - 8.8.8.8
        - 8.8.4.4
      links:
        - neomysql
        - neoredis
        - neorabbit
        - neosocketio
#        - neoelasticsearch
      environment:
        - PHP_XDEBUG_ENABLED=1 # Set 1 to enable.
#        - XDEBUG_CONFIG= remote_host=192.168.254.254
#        - VIRTUAL_HOST=*.caumes.lan,*.neonovis.lan
    neomysql:
      image: mysql/mysql-server:5.7
      container_name: neomysql
      volumes:
        - /home/projects:/home/projects
        - /var/log/mysql:/var/log/mysql
        - /var/lib/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: mypass
      ports:
        - "3306:3306"
    neoredis:
      image: redis:4
      container_name: neoredis
      command: redis-server --requirepass mypass
      ports:
        - "6379:6379"
    neorabbit:
      image: rabbitmq:3.7-management
      container_name: neorabbit
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      ports:
        - "4369:4369"
        - "5671:5671"
        - "5672:5672"
        - "25672:25672"
        - "15672:15672"
    neosocketio:
      image: neosocketio
      container_name: neosocketio
#      extra_hosts:
#      - "www4.neonovis.lan:neoweb"
      volumes:
          - /home/projects:/home/projects
      expose:
      - "8585"
      ports:
      - "8585:8585"
#    neoelasticsearch:
#      image: elasticsearch
#      container_name: neoelasticsearch
#      volumes:
#        - /home/projects/esdata:/usr/share/elasticsearch/data
#      expose:
#      - "9200"
#      - "9300"
#      ports:
#      - "9200:9200"

#networks:
#  neo:
#      external: true
#      name: neo
